// ─────────────────────────────────────────────────────────────────────────────
// Single-file HTML report — the "black box recorder" viewer.
//
// Renders the ledger into one self-contained, dependency-free HTML page with a
// dark-luxury treatment (deep black + amber). No network, no build step.
// ─────────────────────────────────────────────────────────────────────────────

import type { Receipt } from "./types.ts";
import type { ChainVerification } from "./hash.ts";

const COLORS: Record<string, string> = {
  block: "#ff5c5c",
  ask: "#e0a64a",
  allow: "#5ad19a",
};

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function renderReport(receipts: readonly Receipt[], chain: ChainVerification): string {
  const blocked = receipts.filter((r) => r.decision === "block").length;
  const asked = receipts.filter((r) => r.decision === "ask").length;
  const sessions = new Set(receipts.map((r) => r.sessionId)).size;

  const rows = receipts
    .slice()
    .reverse()
    .map((r) => {
      const c = COLORS[r.decision] ?? "#888";
      return `<tr>
        <td class="seq">#${r.seq}</td>
        <td class="ts">${esc(r.ts.replace("T", " ").replace(/\.\d+Z$/, ""))}</td>
        <td><span class="pill" style="--c:${c}">${esc(r.decision)}</span></td>
        <td class="tool">${esc(r.toolName)}</td>
        <td class="summary"><code>${esc(r.summary)}</code><div class="reason">${esc(r.reason)} <span class="rule">${esc(r.rule)}</span></div></td>
      </tr>`;
    })
    .join("\n");

  const chainBadge = chain.ok
    ? `<span class="badge ok">✓ chain intact — ${receipts.length} receipts verified</span>`
    : `<span class="badge bad">✗ TAMPER DETECTED at receipt #${chain.firstBrokenIndex}</span>`;

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>leash · agent flight recorder</title>
<style>
  :root { --bg:#0a0a0a; --surface:#141414; --line:#262626; --text:#ededed; --muted:#8a8a8a; --accent:#d4a574; }
  * { box-sizing:border-box; }
  body { margin:0; background:var(--bg); color:var(--text); font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace; }
  header { padding:32px 28px 20px; border-bottom:1px solid var(--line); }
  h1 { margin:0; font-size:22px; letter-spacing:.5px; }
  h1 .dog { color:var(--accent); }
  .sub { color:var(--muted); margin-top:4px; }
  .stats { display:flex; gap:28px; padding:20px 28px; flex-wrap:wrap; }
  .stat { }
  .stat .n { font-size:28px; font-weight:600; }
  .stat .l { color:var(--muted); font-size:12px; text-transform:uppercase; letter-spacing:1px; }
  .stat.block .n { color:${COLORS.block}; }
  .stat.ask .n { color:${COLORS.ask}; }
  .badge { display:inline-block; padding:6px 12px; border-radius:6px; font-size:12px; margin:0 28px 12px; }
  .badge.ok { background:rgba(90,209,154,.12); color:${COLORS.allow}; }
  .badge.bad { background:rgba(255,92,92,.15); color:${COLORS.block}; }
  table { width:100%; border-collapse:collapse; }
  th,td { text-align:left; padding:10px 14px; border-bottom:1px solid var(--line); vertical-align:top; }
  th { color:var(--muted); font-weight:500; font-size:11px; text-transform:uppercase; letter-spacing:1px; position:sticky; top:0; background:var(--bg); }
  td.seq { color:var(--muted); } td.ts { color:var(--muted); white-space:nowrap; }
  td.tool { color:var(--accent); }
  .pill { color:var(--c); border:1px solid var(--c); border-radius:999px; padding:1px 10px; font-size:12px; text-transform:uppercase; }
  .summary code { color:var(--text); word-break:break-all; }
  .reason { color:var(--muted); font-size:12px; margin-top:3px; }
  .rule { color:#5a5a5a; }
  footer { color:#444; padding:24px 28px; font-size:12px; }
</style></head>
<body>
  <header>
    <h1><span class="dog">🐕</span> leash <span style="color:var(--muted);font-size:14px">· agent flight recorder</span></h1>
    <div class="sub">Tamper-evident record of every action your coding agent took.</div>
  </header>
  ${chainBadge}
  <div class="stats">
    <div class="stat"><div class="n">${receipts.length}</div><div class="l">actions</div></div>
    <div class="stat block"><div class="n">${blocked}</div><div class="l">blocked</div></div>
    <div class="stat ask"><div class="n">${asked}</div><div class="l">held for review</div></div>
    <div class="stat"><div class="n">${sessions}</div><div class="l">sessions</div></div>
  </div>
  <table>
    <thead><tr><th>#</th><th>time</th><th>decision</th><th>tool</th><th>action</th></tr></thead>
    <tbody>${rows || `<tr><td colspan="5" style="color:var(--muted);padding:40px;text-align:center">No actions recorded yet. Wire the hook and run your agent.</td></tr>`}</tbody>
  </table>
  <footer>Generated by leash · the log is the source of truth, this page is just a view of it.</footer>
</body></html>`;
}
